<?php $this->load->view('layout/header'); ?>

<div class="header-2">[ 책을 읽는 습관을 가지자 ]</div>
<div class="home-container">
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis magnam laborum sed repudiandae id ut laudantium expedita perferendis enim doloribus. Amet vel illum ea enim nulla, nesciunt dicta ut voluptatum?
	Non soluta beatae, aut reiciendis numquam veritatis est sapiente labore! Ipsa excepturi voluptatem magni est quasi accusamus incidunt odit inventore! Recusandae excepturi quos esse praesentium eveniet voluptatibus neque rem ipsa?
	Exercitationem, optio tempore? Tempore voluptatem optio, error fugiat adipisci culpa harum quisquam ratione porro inventore ex quos incidunt assumenda necessitatibus cum quia. Ab a fugit, incidunt vero commodi similique culpa.
	Alias aspernatur nulla laudantium possimus obcaecati cupiditate in fugit consequatur nihil! Repellat accusamus aliquid maxime cum? Eius est minus asperiores enim impedit. Incidunt dolorum assumenda nesciunt vero recusandae quibusdam fugiat?
	Voluptas, deleniti mollitia labore repellat saepe quae corporis nostrum eum dolore ipsam, itaque reprehenderit dolor voluptatum tempora unde debitis dolorem omnis facilis maxime? Totam ipsa eum fugit aperiam sequi illum.
	Sunt quas sapiente eius distinctio saepe facere officia laudantium. Eligendi quasi beatae quam odio dicta ipsa commodi praesentium delectus omnis consectetur cupiditate excepturi laudantium pariatur nulla, consequuntur blanditiis, a sunt.
	Perferendis dolorum atque doloremque odio, accusamus quibusdam qui dolor nulla exercitationem quidem blanditiis maiores sint maxime tenetur reprehenderit, laudantium nisi sequi. Placeat magnam impedit non magni nobis, quod nisi quae!
	Fugit ad corporis adipisci officiis, temporibus molestias. Aspernatur, earum? Iure sed ullam odio, obcaecati maxime delectus tempora quasi similique adipisci atque, facilis harum? Laboriosam id explicabo tempore, corrupti repudiandae exercitationem.
	Culpa maxime incidunt, perferendis, repellat harum non, tempora quas laboriosam placeat eveniet magni voluptatem consequatur assumenda corrupti cupiditate? Dolore perferendis sed possimus iure expedita. Officia, sint. Illo eaque commodi quo!
	Dolorum, aliquid ratione? Maiores reprehenderit suscipit vitae error ea consectetur perspiciatis ipsam, necessitatibus pariatur unde ullam eveniet eum iste sapiente delectus magni voluptates. Soluta provident, vitae ipsam saepe culpa rerum?
	Voluptates, aspernatur beatae. Adipisci, excepturi assumenda dolores sit tempore enim natus neque beatae, aliquid esse aliquam est dignissimos dolorem, fugiat blanditiis quia voluptas sunt iure expedita odio? Quibusdam, fugiat mollitia!
	Et quae labore maiores illo officiis doloribus dolorum magnam sit inventore aspernatur excepturi nobis molestiae, laboriosam blanditiis dignissimos quibusdam esse est beatae eveniet asperiores ad cupiditate, odit qui. Doloribus, eligendi?
	Optio magni cupiditate inventore. Doloremque maxime hic ipsum reiciendis placeat reprehenderit eos et odit nobis aspernatur vero voluptatum ut impedit ullam facilis soluta unde voluptates, dicta magnam illum! Adipisci, ducimus.
	Omnis alias hic fugiat exercitationem commodi eaque, nesciunt accusamus illum labore laudantium dicta debitis nemo aut in? Hic voluptatum, aliquam aut eveniet ipsum vitae, suscipit error at nam laboriosam provident.
	Unde sunt eius iusto distinctio nobis ad praesentium fugit cum recusandae. Officia commodi aliquid, qui quia iure sed nulla nobis quis, rerum id culpa hic dicta placeat temporibus. Ab, molestias!
	Numquam aliquid eum, in nihil iste rerum voluptates obcaecati, adipisci eius reiciendis accusamus rem inventore unde ipsam tempora dolorem iure tenetur aperiam, nobis atque libero? Recusandae exercitationem adipisci repudiandae nulla.
	Voluptates placeat hic illo at cum quibusdam molestias velit corrupti, unde laborum non? Cum deleniti, atque doloribus ipsum debitis aut laudantium nam dolores minima, perspiciatis porro. Deleniti autem praesentium delectus!
	Totam mollitia, ipsam labore, obcaecati ad, hic optio accusamus eveniet fugiat quia repudiandae facilis at et inventore illum alias? Consequuntur provident vero, maiores corrupti praesentium a itaque quae dolore totam.
	Deleniti mollitia at in obcaecati facilis maxime maiores asperiores nemo sit architecto placeat totam voluptatibus odit dolores quam suscipit quod, itaque error quis. Neque quos, praesentium commodi est ducimus quae!
	Tenetur ipsa vitae sapiente aut rerum exercitationem fugiat, illum eos impedit veniam ipsam veritatis voluptatibus nemo sit. Rem saepe quas quod? Officia at explicabo dolores aliquid iure nesciunt repudiandae a!
	Iusto quidem vero dolore deserunt esse. Tempore amet recusandae incidunt perspiciatis id, vero eos aliquam quibusdam reprehenderit inventore molestias! Id tempora architecto assumenda neque! Dolores sunt obcaecati velit eos laboriosam.
	Enim ipsam voluptates tenetur quam, odit, necessitatibus similique exercitationem sequi nulla est blanditiis, fugit saepe doloribus facilis consectetur explicabo quis excepturi commodi architecto vero. Repudiandae aut assumenda sunt minus asperiores!
	Voluptatem omnis, fugiat corrupti iusto perspiciatis saepe illum, vero placeat quam quis ab sequi nulla praesentium repellendus beatae iste excepturi quasi rem? Quas excepturi quibusdam molestiae aut tempora, obcaecati non!
	Ducimus aspernatur repudiandae autem. Quae ipsa voluptatem est nulla. Non provident inventore tempore necessitatibus dolore sint eaque. Eum et minus reprehenderit cum error atque suscipit consequuntur natus, illo sequi ullam?
	At, rem reiciendis. Earum, culpa minima temporibus quod labore ut, repellendus voluptatem deleniti eos molestias architecto voluptas dolores accusamus corrupti odio quas dignissimos quisquam aperiam corporis ratione. Eius, corrupti numquam.
	Maiores repudiandae earum, corporis vero placeat reprehenderit suscipit eaque fuga esse, assumenda unde ullam necessitatibus eligendi corrupti dolore quo vitae, illo quam in! Eius fuga facilis corrupti quidem harum deserunt.
	Ipsum quo blanditiis voluptatem delectus praesentium quia molestias eligendi placeat sit. Ratione provident sit pariatur nemo debitis eaque, quibusdam quod vel aliquid recusandae saepe. Adipisci error fugit iste dolores esse!
	Totam, voluptatem culpa. Quidem, facilis? Suscipit animi ratione ipsa, nam alias dolorum porro nemo possimus reprehenderit sit obcaecati. Rerum, totam voluptas mollitia nemo cum earum ipsum commodi consequatur blanditiis eius.
	Facere eum aspernatur quidem esse qui accusantium mollitia necessitatibus quibusdam fugiat soluta natus praesentium voluptas eos possimus magni, ea repellat tenetur sed assumenda est ullam officia enim! Totam, iure provident?
	Officiis asperiores id laudantium nisi obcaecati non, voluptates ducimus ratione nulla cupiditate enim rerum minus possimus corporis voluptatem saepe voluptatum nostrum magni maiores autem nam rem fuga suscipit. Perferendis, sequi?
	Optio quas incidunt ipsum aut earum. Quos repellat recusandae incidunt sint, nulla esse aperiam sunt beatae aliquam! Aperiam commodi vel laudantium recusandae incidunt nostrum sit placeat accusantium. Necessitatibus, provident numquam.
	A reiciendis consectetur, perferendis placeat sit doloremque alias accusamus, consequatur aut, magnam nesciunt possimus harum sapiente dolore ullam. Quidem tenetur neque, esse dolorem reprehenderit ipsa rerum quos non totam atque?
	Excepturi, blanditiis recusandae. Eveniet, autem provident ipsam amet nobis non quis saepe eligendi perspiciatis, quibusdam molestiae placeat porro. Provident assumenda pariatur cupiditate dolorem in. Commodi reprehenderit neque voluptatem excepturi unde?
	Sed unde, laudantium ullam dolorum culpa sunt nam neque soluta repellendus? Asperiores autem reprehenderit porro consequatur provident laboriosam, veritatis nulla rem quam, ratione hic, ipsa voluptas velit! Aliquid, voluptates delectus.
	Inventore reiciendis odit, eum labore totam itaque repellat vero tempora exercitationem provident sit quia fuga ab suscipit deleniti aliquid voluptatum vitae voluptatibus. Architecto repudiandae ad obcaecati quo earum, aspernatur nemo.
	Dolore voluptatum aut nemo minima alias laborum ab ut commodi error nulla vero nihil temporibus voluptate exercitationem eveniet, autem dolores animi? A, quo fuga pariatur autem asperiores esse officia natus!
	Reprehenderit, vitae doloribus. Recusandae esse laborum sed? Tempore debitis nulla magni veritatis quod. Nihil in quas quasi asperiores, assumenda officiis vel aliquam dolorem, error amet incidunt perferendis ad exercitationem sint?

</div>